disabled_rules:
- trailing_whitespace
type_name:
  min_length: 1
line_length:
  warning: 700
  error: 1000
function_body_length:
  warning: 400 # default 40
  error: 1000 # default 100
function_parameter_count:
  warning: 20
  error: 25
identifier_name:
  allowed_symbols: ["_"]
  validates_start_with_lowercase: false
  min_length: 1

opt_in_rules: # some rules are only opt-in
  - shorthand_operator
  
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
